### ISSUE TITLE
No app.js in the build directory

### ISSUE THREAD

**Issue by ozyman42** [router5/examples#10]
I built the react-redux example by running `npm run build -- --app react-redux`, then started the server as the instructions state by running `http-server -s -p 9000`. I then proceeded to open localhost:9000 in my browser where I was greeted with this error in the developer tools console: `Failed to load resource: the server responded with a status of 404 (Not Found) ... http://localhost:9000/build/app.js`. My guess is that the build tool created a file called `router5-react-redux-example.js` which should have actually been called `app.js`. Could you fix this?

**Comment by troch** [comment]
Fixed it. Use `npm start` (`npm start -- --app <app-name>`) and navigate to http://localhost:8080.
