### ISSUE TITLE
deku redux example

### ISSUE THREAD

**Issue by svnm** [router5/examples#2]
Hi, I was wanting to work on a new set of redux-router5 examples.

I have a set of [redux examples](https://github.com/StevenIseki/redux-examples). The redux-router5 and pets-app both use react, redux and router5. I found router5 much better to use than react-router.

I want to make a set of many redux router5 examples and I want them to be interchangeable between deku and redux, as in having corresponding react and deku versions of each example.

However I don't have a deku redux router5 example to base my examples off.

The main problem is I don't know how to initialize the app with deku equivalent to how it is done in react.

``` js
import { Provider } from 'react-redux';
import { RouterProvider } from 'react-router5'; 

router.start((err, state) => {
    const store = configureStore(router, { router: { route: state }});

    const wrappedApp = (
        <Provider store={ store } >
            <RouterProvider router= { router }>
                <App />
            </RouterProvider>
        </Provider>
    );

    ReactDOM.render(wrappedApp, document.getElementById('root'));
});
```

Also the connect part in the container components

``` js
import { connect } from 'react-redux';
export default connect(mapStateToProps)(PetDetailView);
```

**Comment by troch** [comment]
Hi @StevenIseki,

Great to see you are creating examples using router5, many thanks :+1:.
For using redux with deku, you are missing deku bindings for redux. I am not aware of such package existing and I started to create one (private for now, but I will make it public when it is ready). It basically consists of a deku plugin (to set the store as a source) and a higher-order component (connect) to map state and actions to props and re-render when a change is detected.

**Comment by svnm** [comment]
Thanks @troch I will be very keen to use the deku bindings for redux. Great to hear you are working on it. If you have any code snippets, I would be happy to help out with the deku bindings, if I can work out how to do it. In the meantime I will keep making a few more router5, redux and deku examples.

I guess the higher order component connect will be similar to [connect](https://github.com/rackt/react-redux/blob/master/src/components/connect.js) for react and the provider is similar to [Provider](https://github.com/rackt/react-redux/blob/master/src/components/Provider.js)

**Comment by troch** [comment]
Yes, `connect` higher-order component, but no `Provider` HOC. Instead, I'll write a deku plugin which attaches the store object to the deku tree.

I am still working on it locally, but I will push some commits before the week-end and make the repo public, so you can have a look.

**Comment by troch** [comment]
In the mean time: https://gist.github.com/troch/520eb25dce170a69758a

**Comment by svnm** [comment]
Thanks that looks good, so connect is just a higher order component which has some similarity to the react-redux version but with the lifecycle hook's specific for deku and obviously using virtual-element.

For the deku plugin for attaching the store object to the deku tree, I am not sure exactly how this works, but keen to see some code once you have it going. I can see some discussion on how to create a plugin for deku [here](https://github.com/dekujs/deku/issues/155)

I will be happy to help out with some documentation on the deku-redux repo, and an example if you like once you have the repo started.

**Comment by troch** [comment]
Yes, that is correct. connect is a deku component used as a higher-order component. It has the same functionalities than the react-redux one.

For deku plugins, exactly how it is done in `router5-deku`: https://github.com/router5/deku-router5/blob/master/modules/routerPlugin.js, expect we set `store` and `storeState` (that makes connect a bit leaner by not having to subscribe and unsubscribe to store state changes).

:+1: for docs and example

**Comment by troch** [comment]
- https://github.com/troch/deku-redux, released
- Example with router5 added: https://github.com/router5/examples/tree/master/apps/deku-redux (same old example recycled)
- Live here: http://localhost:8080/docs/with-deku-redux.html

**Comment by svnm** [comment]
Great, awesome work @troch. It is working nicely for me.
I will keep working on some examples and docs over the next few days.

**Comment by troch** [comment]
Closing this
