### ISSUE TITLE
Why create store in router.start callback?

### ISSUE THREAD

**Issue by LabiKyo** [router5/examples#9]
Hi, I'm writing my second router5 project, and I follow redux example and fall into the trap again. I think create store in router.start callback is a bad practice, because router5Middleware add store as additional args, which change router5's own middleware's arguments, but the middleware was called already when router.start, so the middleware have to deal with 2 different arguments.

Now I change my code to create router first, then create store with not initialState, then start router. Router5 reducer can handle router state change after router.start, so it's alright so far.

Is there any reason you do that in the example?

**Comment by troch** [comment]
No, no reason. It's an example I wrote a few months ago, and I have not updated it (you are right about pointing out additional args).

I do the following: create router, create store with router, start router.

PR welcome :)

**Comment by troch** [comment]
Node: additional args is something which will be re-factored in 4.0. It causes composition and re-usability issues (if one wants to share a middleware function)

**Comment by LabiKyo** [comment]
Looking forward to see 4.0. I'd love to send a PR later :)

**Comment by troch** [comment]
Examples have been upgraded to v3, and slightly refactored regarding your comments. v4 is in progress.
